[2015-10-15 12:34:16,507: WARNING/MainProcess] worker@alpha007 ready.
[2015-10-15 12:43:59,007: ERROR/MainProcess] Task nidaba.ocr.tesseract[032d7a30-e236-4abc-a514-e9a590d887fc] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
