[2015-10-15 14:30:42,630: WARNING/MainProcess] worker@alpha007 ready.
[2015-10-15 15:01:18,149: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/async/hub.py", line 267, in create_loop
    tick_callback()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 943, in on_poll_start
    cycle_poll_start()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 302, in on_poll_start
    self._register_LISTEN(channel)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 292, in _register_LISTEN
    self._register(channel, channel.subclient, 'LISTEN')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 268, in _register
    client.connection.connect()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
[2015-10-15 15:01:18,155: WARNING/MainProcess] Restoring 40 unacknowledged message(s).
[2015-10-15 15:01:18,178: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 2.00 seconds...

[2015-10-15 15:01:20,193: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 4.00 seconds...

[2015-10-15 15:01:24,199: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 6.00 seconds...

[2015-10-15 15:01:30,207: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 8.00 seconds...

[2015-10-15 15:01:38,217: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 10.00 seconds...

[2015-10-15 15:01:41,258: ERROR/Worker-31] Connection to Redis lost: Retry (0/20) now.
[2015-10-15 15:01:41,260: ERROR/Worker-31] Connection to Redis lost: Retry (1/20) in 1.00 second.
[2015-10-15 15:01:49,280: ERROR/MainProcess] Task nidaba.ocr.tesseract[b9830654-0b71-46de-8a6d-7696e0781ffd] raised unexpected: ConnectionError('Error 111 connecting to 127.0.0.1:6379. Connection refused.',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 27, in _redis_set_atomically
    pipe.watch(batch_id)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/client.py", line 2601, in watch
    return self.execute_command('WATCH', *names)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/client.py", line 2394, in execute_command
    return self.immediate_execute_command(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/client.py", line 2421, in immediate_execute_command
    conn.send_command(*args)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
[2015-10-15 15:01:52,648: ERROR/MainProcess] Task nidaba.ocr.tesseract[23780449-e91d-4f28-a33b-dac5d56100f3] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:01,679: ERROR/MainProcess] Task nidaba.ocr.tesseract[f4d82919-0d1d-4a26-852e-bea783730bda] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:06,963: ERROR/MainProcess] Task nidaba.ocr.tesseract[5dc834e9-f4b5-4ebb-bef4-0b109911b322] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:14,625: ERROR/MainProcess] Task nidaba.ocr.tesseract[b36dbad5-3011-48d1-aa1a-0f2e07e81724] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:14,630: ERROR/MainProcess] Task nidaba.ocr.tesseract[a413eced-1fb9-4c2e-95ff-2ebbccddd331] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    _redis_set_atomically(batch_id, task_id, 'errors', (nkwargs, e.message))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:15,045: ERROR/MainProcess] Task nidaba.ocr.tesseract[7e45af47-ee09-40d4-a333-b122a1cf66ea] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:15,052: ERROR/MainProcess] Task nidaba.ocr.tesseract[c0640cd5-45d4-4285-8db0-ebd854640d2c] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    _redis_set_atomically(batch_id, task_id, 'errors', (nkwargs, e.message))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:24,148: ERROR/MainProcess] Task nidaba.ocr.tesseract[4f09e92f-5723-4136-9645-f1f9e13c9bf7] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:35,032: ERROR/MainProcess] Task nidaba.ocr.tesseract[a311e189-5ad4-46c5-a565-5a9ab6b5db5e] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:36,606: ERROR/MainProcess] Task nidaba.ocr.tesseract[1e9941c0-e292-4656-aa94-901dac8b4450] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:36,613: ERROR/MainProcess] Task nidaba.ocr.tesseract[c3f33021-8a8b-46b0-93a8-36f6d3a1e96b] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    _redis_set_atomically(batch_id, task_id, 'errors', (nkwargs, e.message))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:37,262: ERROR/MainProcess] Task nidaba.ocr.tesseract[ec8fc272-3580-41b4-864e-3223ce2d1f36] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:02:46,639: ERROR/MainProcess] Task nidaba.ocr.tesseract[619757cc-e1bf-4ece-b0b9-38b4925e528b] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:05,581: ERROR/MainProcess] Task nidaba.ocr.tesseract[d56a6581-86d5-47b4-8fbc-b17f4051e274] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:11,852: ERROR/MainProcess] Task nidaba.ocr.tesseract[5c6b6616-ddf4-4683-a65c-0497c7ef0d34] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:14,818: ERROR/MainProcess] Task nidaba.ocr.tesseract[c82715fe-87e9-496c-9f7c-e17bf5b4b2ad] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:16,811: ERROR/MainProcess] Task nidaba.ocr.tesseract[8241e709-116d-4764-b9e1-5426c1a90613] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:16,821: ERROR/MainProcess] Task nidaba.ocr.tesseract[3ec7c0a1-f5c4-478c-90bb-bd565f82d5da] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    _redis_set_atomically(batch_id, task_id, 'errors', (nkwargs, e.message))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:17,788: ERROR/MainProcess] Task nidaba.ocr.tesseract[dc28745c-8e58-4084-840f-da2ad189043f] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:22,434: ERROR/MainProcess] Task nidaba.ocr.tesseract[1939df85-9a99-415a-8c6f-f6828e037278] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:29,312: ERROR/MainProcess] Task nidaba.ocr.tesseract[69d56349-aead-4c76-9794-701cfdaf4a88] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:30,491: ERROR/MainProcess] Task nidaba.ocr.tesseract[92d4a0db-7698-4b1c-9dbb-19427b87057c] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:32,412: ERROR/MainProcess] Task nidaba.ocr.tesseract[aa86d503-119f-48f5-a8a2-58a4820f8390] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:32,918: ERROR/MainProcess] Task nidaba.ocr.tesseract[9d37a501-500c-4bc3-9ae4-c3bff8230394] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:36,308: ERROR/MainProcess] Task nidaba.ocr.tesseract[948f55aa-fd84-4d74-b8b7-ab670cc6737f] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:41,589: ERROR/MainProcess] Task nidaba.ocr.tesseract[8a3db611-50ad-4cc6-9747-832ef387e67d] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:41,594: ERROR/MainProcess] Task nidaba.ocr.tesseract[60ffc53f-d74c-4837-a7dd-d5f2d786238d] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    _redis_set_atomically(batch_id, task_id, 'errors', (nkwargs, e.message))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:41,951: ERROR/MainProcess] Task nidaba.ocr.tesseract[0914bd67-b244-44e9-b3de-bb038c8c958f] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:43,433: ERROR/MainProcess] Task nidaba.ocr.tesseract[f1a53bfe-92bd-42c4-9f1a-dde21916574e] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    _redis_set_atomically(batch_id, task_id, 'errors', (nkwargs, e.message))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:43,566: ERROR/MainProcess] Task nidaba.ocr.tesseract[c7dc1993-6eff-4e20-8635-1903a3542b76] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:43,969: ERROR/MainProcess] Task nidaba.ocr.tesseract[58fba8e1-9101-4aef-9b3b-24359a8810e0] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:46,155: ERROR/MainProcess] Task nidaba.ocr.tesseract[5cc8a041-35f6-4c45-9ea0-efb7f578462e] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:49,039: ERROR/MainProcess] Task nidaba.ocr.tesseract[a684da41-a779-404f-ad83-185a82d1fe75] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:54,482: ERROR/MainProcess] Task nidaba.ocr.tesseract[ba4dbdfa-e166-4226-9bcd-4c70b8062a84] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:54,487: ERROR/MainProcess] Task nidaba.segmentation.tesseract[3a10f4c9-5b6c-471e-a8e7-9f33195b244f] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    _redis_set_atomically(batch_id, task_id, 'errors', (nkwargs, e.message))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:03:58,335: ERROR/MainProcess] Task nidaba.ocr.tesseract[6a4373ca-fb37-4468-9021-1bf6c3561adf] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:04:02,708: ERROR/MainProcess] Task nidaba.ocr.tesseract[58e11688-f989-46f0-8527-8fdf58780169] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:04:02,713: ERROR/MainProcess] Task nidaba.ocr.tesseract[261759b6-998d-4c57-9bcf-64f6f024374e] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    _redis_set_atomically(batch_id, task_id, 'errors', (nkwargs, e.message))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 15:04:03,907: ERROR/MainProcess] Task nidaba.ocr.tesseract[32175855-3fd3-4d53-871f-e9ca01852563] raised unexpected: TypeError('expected string or buffer',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 92, in __call__
    _redis_set_atomically(batch_id, task_id, 'state', 'SUCCESS')
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 28, in _redis_set_atomically
    batch_struct = json.loads(pipe.get(batch_id))
  File "/opt/shared/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/shared/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2015-10-15 16:30:31,746: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/async/hub.py", line 267, in create_loop
    tick_callback()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 943, in on_poll_start
    cycle_poll_start()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 300, in on_poll_start
    self._register_BRPOP(channel)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 283, in _register_BRPOP
    self._register(*ident)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 268, in _register
    client.connection.connect()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
[2015-10-15 16:30:31,757: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 2.00 seconds...

[2015-10-15 16:30:33,762: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 4.00 seconds...

[2015-10-15 16:30:37,769: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 6.00 seconds...

[2015-10-15 16:30:43,777: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 8.00 seconds...

[2015-10-15 16:30:51,788: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 10.00 seconds...

[2015-10-15 16:31:01,802: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 12.00 seconds...

[2015-10-15 16:40:18,562: ERROR/MainProcess] Task nidaba.ocr.tesseract[deee4ac7-bad6-480b-903d-1ba099dd18ee] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 16:40:31,423: ERROR/MainProcess] Task nidaba.ocr.tesseract[7352a1f1-f243-43c6-89a9-6ddd8d22be31] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 16:41:11,904: ERROR/MainProcess] Task nidaba.ocr.tesseract[4e038210-2cf0-4f5d-a202-fd34cb4e3c6f] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 16:42:06,964: ERROR/MainProcess] Task nidaba.ocr.tesseract[6f53ed9e-60d3-49b7-96a3-edc4699745c6] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 16:46:36,723: ERROR/MainProcess] Task nidaba.ocr.tesseract[4b803a35-212e-461a-8b94-799dcf32ebd4] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 20:36:24,668: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/async/hub.py", line 267, in create_loop
    tick_callback()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 943, in on_poll_start
    cycle_poll_start()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 300, in on_poll_start
    self._register_BRPOP(channel)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 283, in _register_BRPOP
    self._register(*ident)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kombu/transport/redis.py", line 268, in _register
    client.connection.connect()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
[2015-10-15 20:36:24,679: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 2.00 seconds...

[2015-10-15 20:36:26,684: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 4.00 seconds...

[2015-10-15 20:36:30,691: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 6.00 seconds...

[2015-10-15 20:36:36,699: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379//: Error 111 connecting to 127.0.0.1:6379. Connection refused..
Trying again in 8.00 seconds...

[2015-10-15 20:52:46,329: ERROR/MainProcess] Task nidaba.ocr.tesseract[1cc1a94b-c636-4f62-a271-83e4a93ffbbc] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 20:56:45,732: ERROR/MainProcess] Task nidaba.ocr.tesseract[2a4eee66-10f9-411a-a7c1-c8826b08fce2] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:00:15,851: ERROR/MainProcess] Task nidaba.ocr.tesseract[9ed34731-8d51-4d92-b051-37a868d9a7f9] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:00:25,577: ERROR/MainProcess] Task nidaba.ocr.tesseract[8fe5bffd-2775-4eed-ad9a-ab8089baa5d1] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:01:11,335: ERROR/MainProcess] Task nidaba.ocr.tesseract[c2244333-d2ec-44a0-9bf3-90ae11e68e6b] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:02:08,049: ERROR/MainProcess] Task nidaba.ocr.tesseract[c2456452-8377-474b-86c6-b56ee29fca9b] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:02:37,348: ERROR/MainProcess] Task nidaba.ocr.tesseract[5e6d813a-5821-40d4-b623-8cb0416f3f21] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:04:58,135: ERROR/MainProcess] Task nidaba.ocr.tesseract[550fbed3-9b6f-4b7b-9bf7-e7b2b2c01cab] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:05:07,035: ERROR/MainProcess] Task nidaba.ocr.tesseract[97e38fce-4a5c-4ebb-a07b-8faf362bf8ad] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:05:41,119: ERROR/MainProcess] Task nidaba.ocr.tesseract[94e68fae-e3cf-4ea2-9dd8-edd9081a814f] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:07:17,082: ERROR/MainProcess] Task nidaba.ocr.tesseract[4867e78f-c33d-468d-87d7-66572eaaa917] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:07:29,920: ERROR/MainProcess] Task nidaba.ocr.tesseract[bb0554a9-49fd-4497-8f22-3ddef44f50a6] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:08:29,256: ERROR/MainProcess] Task nidaba.ocr.tesseract[6990b95f-f757-4350-8d3c-aaa8c1a8e820] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:08:37,185: ERROR/MainProcess] Task nidaba.ocr.tesseract[29f995d2-7b35-4a18-8315-9e2570d72041] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:11:38,885: ERROR/MainProcess] Task nidaba.ocr.tesseract[8c437461-a32f-4749-ac6c-b02e276c83af] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:13:04,561: ERROR/MainProcess] Task nidaba.ocr.tesseract[24c5e49d-56d7-4277-b790-849b1bcc9ba4] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:13:30,840: ERROR/MainProcess] Task nidaba.ocr.tesseract[7fc8b4f6-d05f-4ce1-a8c7-3bcdafb99f05] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:14:53,672: ERROR/MainProcess] Task nidaba.ocr.tesseract[81a216fa-d9f6-40ba-98f6-ab6f0addb999] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:15:13,801: ERROR/MainProcess] Task nidaba.ocr.tesseract[ad9f23fe-3672-4e10-918e-f3dda4e87731] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:15:55,936: ERROR/MainProcess] Task nidaba.ocr.tesseract[f76a8a62-2ac0-4403-a056-35db8924f1fb] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-15 21:16:25,676: ERROR/MainProcess] Task nidaba.ocr.tesseract[cc9aa8e2-70c0-4a9a-bd93-04cb9c11daa6] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 87, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 372, in ocr_tesseract
    ocr_capi(image_path, result_path, seg, languages, extended)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 420, in ocr_capi
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
